# Generated by Django 4.2.13 on 2024-06-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellnessTracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcoholhabit',
            name='alcohol_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Did you drink any alcohol? (amount)'),
        ),
        migrations.AlterField(
            model_name='cigarettehabit',
            name='cigarettes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='How many cigarettes did you smoke?'),
        ),
        migrations.AlterField(
            model_name='coffehabit',
            name='coffee_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='How much coffee did you drink?'),
        ),
        migrations.AlterField(
            model_name='sports',
            name='exercise_times',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='How long did you exercise?'),
        ),
    ]
