# Generated by Django 4.2.13 on 2024-06-16 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wellnessTracker", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coffee_amount",
                    models.PositiveIntegerField(
                        default=0, verbose_name="How much coffee did you drink?"
                    ),
                ),
                (
                    "coffee_unit",
                    models.CharField(
                        choices=[("ml", "ml"), ("l", "l")],
                        default="ml",
                        max_length=2,
                        verbose_name="Unit of coffee",
                    ),
                ),
                (
                    "cigarettes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="How many cigarettes did you smoke?"
                    ),
                ),
                (
                    "cigarette_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("choose-type", "Choose type"),
                            ("full-flavor", "Full Flavor"),
                            ("light", "Light"),
                            ("ultra-light", "Ultra Light"),
                            ("menthol", "Menthol"),
                            ("flavored", "Flavored"),
                            ("heated-tobacco", "Heated Tobacco Products (HTP)"),
                            ("e-cigarette", "E-Cigarette (Electronic Cigarette)"),
                            ("roll-your-own", "Roll-Your-Own"),
                            ("nicotine-free", "Nicotine-Free"),
                            ("premium", "Premium"),
                            ("organic", "Organic"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Type of cigarette",
                    ),
                ),
                (
                    "alcohol_amount",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Did you drink any alcohol? (amount)"
                    ),
                ),
                (
                    "alcohol_unit",
                    models.CharField(
                        choices=[("ml", "ml"), ("l", "l")],
                        default="ml",
                        max_length=2,
                        verbose_name="Unit of alcohol",
                    ),
                ),
                (
                    "alcohol_type",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("beer", "Beer"),
                            ("wine", "Wine"),
                            ("vodka", "Vodka"),
                            ("whiskey", "Whiskey"),
                            ("rum", "Rum"),
                            ("tequila", "Tequila"),
                            ("gin", "Gin"),
                            ("brandy", "Brandy"),
                            ("champagne", "Champagne"),
                            ("cider", "Cider"),
                            ("absinthe", "Absinthe"),
                            ("liqueur", "Liqueur"),
                            ("sake", "Sake"),
                            ("vermouth", "Vermouth"),
                            ("mead", "Mead"),
                            ("sherry", "Sherry"),
                            ("port", "Port"),
                            ("cocktail", "Cocktail"),
                            ("schnapps", "Schnapps"),
                            ("perry", "Perry"),
                            ("moonshine", "Moonshine"),
                            ("armagnac", "Armagnac"),
                            ("calvados", "Calvados"),
                            ("grappa", "Grappa"),
                            ("aquavit", "Aquavit"),
                            ("baijiu", "Baijiu"),
                            ("ouzo", "Ouzo"),
                            ("rakia", "Rakia"),
                            ("tequila-sunrise", "Tequila Sunrise"),
                            ("martini", "Martini"),
                            ("manhattan", "Manhattan"),
                            ("margarita", "Margarita"),
                            ("mojito", "Mojito"),
                            ("bloody-mary", "Bloody Mary"),
                            ("pina-colada", "Piña Colada"),
                            ("cosmopolitan", "Cosmopolitan"),
                            ("old-fashioned", "Old Fashioned"),
                        ],
                        max_length=20,
                        verbose_name="Type of alcohol",
                    ),
                ),
                (
                    "exercise_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="How long did you exercise?"
                    ),
                ),
                (
                    "exercise_unit",
                    models.CharField(
                        choices=[("minutes", "minutes"), ("hours", "hours")],
                        default="minutes",
                        max_length=8,
                        verbose_name="Unit of sports",
                    ),
                ),
                (
                    "exercise_type",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("gym", "Gym"),
                            ("running", "Running"),
                            ("cycling", "Cycling"),
                            ("swimming", "Swimming"),
                            ("basketball", "Basketball"),
                            ("soccer", "Soccer"),
                            ("tennis", "Tennis"),
                            ("yoga", "Yoga"),
                            ("pilates", "Pilates"),
                            ("hiking", "Hiking"),
                            ("climbing", "Climbing"),
                            ("dancing", "Dancing"),
                            ("boxing", "Boxing"),
                            ("martial-arts", "Martial Arts"),
                            ("weightlifting", "Weightlifting"),
                            ("crossfit", "CrossFit"),
                            ("aerobics", "Aerobics"),
                            ("rowing", "Rowing"),
                            ("skiing", "Skiing"),
                            ("snowboarding", "Snowboarding"),
                            ("skating", "Skating"),
                            ("surfing", "Surfing"),
                            ("kayaking", "Kayaking"),
                            ("golf", "Golf"),
                            ("cricket", "Cricket"),
                            ("rugby", "Rugby"),
                            ("baseball", "Baseball"),
                            ("volleyball", "Volleyball"),
                            ("badminton", "Badminton"),
                            ("table-tennis", "Table Tennis"),
                            ("archery", "Archery"),
                            ("fencing", "Fencing"),
                            ("horse-riding", "Horse Riding"),
                            ("gymnastics", "Gymnastics"),
                            ("triathlon", "Triathlon"),
                            ("bouldering", "Bouldering"),
                        ],
                        max_length=20,
                        verbose_name="Type of exercise",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Time when the interface was last updated",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mood",
            name="slept_scale",
            field=models.IntegerField(
                choices=[
                    (0, "0"),
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10"),
                ],
                default=0,
                help_text="How long user slept today",
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="mood",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="wellnessTracker.mood",
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="mood",
            name="scale",
            field=models.IntegerField(
                choices=[
                    (0, "0"),
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10"),
                ],
                default=0,
                help_text="How user felt today",
            ),
        ),
        migrations.AddField(
            model_name="day",
            name="habit",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="wellnessTracker.habit",
            ),
        ),
    ]
