# Generated by Django 4.2.13 on 2024-06-18 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wellnessTracker', '0002_habit_mood_slept_scale_alter_day_mood_alter_day_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wellnessTracker.habit'),
        ),
        migrations.AlterField(
            model_name='day',
            name='mood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wellnessTracker.mood'),
        ),
        migrations.AlterField(
            model_name='day',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='habit',
            name='alcohol_amount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Did you drink any alcohol? (amount)'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='alcohol_unit',
            field=models.CharField(blank=True, choices=[('ml', 'ml'), ('l', 'l')], default='ml', max_length=2, null=True, verbose_name='Unit of alcohol'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='cigarettes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='How many cigarettes did you smoke?'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='coffee_amount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='How much coffee did you drink?'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='coffee_unit',
            field=models.CharField(blank=True, choices=[('ml', 'ml'), ('l', 'l')], default='ml', max_length=2, null=True, verbose_name='Unit of coffee'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='exercise_minutes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='How long did you exercise?'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='exercise_unit',
            field=models.CharField(blank=True, choices=[('minutes', 'minutes'), ('hours', 'hours')], default='minutes', max_length=8, null=True, verbose_name='Unit of sports'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='emotions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('excited', 'Excited'), ('nervous', 'Nervous'), ('scared', 'Scared'), ('relaxed', 'Relaxed'), ('bored', 'Bored'), ('content', 'Content'), ('curious', 'Curious'), ('anxious', 'Anxious'), ('confused', 'Confused'), ('surprised', 'Surprised'), ('grateful', 'Grateful'), ('frustrated', 'Frustrated'), ('jealous', 'Jealous'), ('lonely', 'Lonely'), ('proud', 'Proud'), ('ashamed', 'Ashamed'), ('guilty', 'Guilty'), ('embarrassed', 'Embarrassed'), ('disappointed', 'Disappointed'), ('inspired', 'Inspired'), ('amused', 'Amused'), ('sympathetic', 'Sympathetic'), ('thoughtful', 'Thoughtful'), ('energetic', 'Energetic'), ('overwhelmed', 'Overwhelmed'), ('hopeful', 'Hopeful')], help_text='Which emotions did user felt', max_length=100),
        ),
        migrations.AlterField(
            model_name='mood',
            name='note',
            field=models.TextField(blank=True, help_text='Custom user note'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='scale',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=0, help_text='How user felt today', null=True),
        ),
        migrations.AlterField(
            model_name='mood',
            name='slept_scale',
            field=models.IntegerField(blank=True, choices=[(0.0, '0.0'), (0.5, '0.5'), (1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0'), (5.5, '5.5'), (6.0, '6.0'), (6.5, '6.5'), (7.0, '7.0'), (7.5, '7.5'), (8.0, '8.0'), (8.5, '8.5'), (9.0, '9.0'), (9.5, '9.5'), (10.0, '10.0')], default=0, help_text='How long user slept today', null=True),
        ),
    ]
