# Generated by Django 4.2.13 on 2024-06-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wellnessTracker", "0002_alter_alcoholhabit_alcohol_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="moodscale",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
