# Generated by Django 4.2.13 on 2024-06-18 11:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellnessTracker', '0003_alter_day_habit_alter_day_mood_alter_day_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='slept_scale',
            field=models.FloatField(blank=True, choices=[(Decimal('0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5'), '5.0'), (Decimal('5.5'), '5.5'), (Decimal('6'), '6.0'), (Decimal('6.5'), '6.5'), (Decimal('7'), '7.0'), (Decimal('7.5'), '7.5'), (Decimal('8'), '8.0'), (Decimal('8.5'), '8.5'), (Decimal('9'), '9.0'), (Decimal('9.5'), '9.5'), (Decimal('10'), '10.0'), (Decimal('10.5'), '10.5'), (Decimal('11'), '11.0'), (Decimal('11.5'), '11.5'), (Decimal('12'), '12.0'), (Decimal('12.5'), '12.5'), (Decimal('13'), '13.0'), (Decimal('13.5'), '13.5'), (Decimal('14'), '14.0'), (Decimal('14.5'), '14.5'), (Decimal('15'), '15.0'), (Decimal('15.5'), '15.5'), (Decimal('16'), '16.0'), (Decimal('16.5'), '16.5'), (Decimal('17'), '17.0'), (Decimal('17.5'), '17.5'), (Decimal('18'), '18.0'), (Decimal('18.5'), '18.5'), (Decimal('19'), '19.0'), (Decimal('19.5'), '19.5'), (Decimal('20'), '20.0'), (Decimal('20.5'), '20.5'), (Decimal('21'), '21.0'), (Decimal('21.5'), '21.5'), (Decimal('22'), '22.0'), (Decimal('22.5'), '22.5'), (Decimal('23'), '23.0'), (Decimal('23.5'), '23.5'), (Decimal('24'), '24.0')], default=0, help_text='How long user slept today', null=True),
        ),
    ]
