# Generated by Django 4.2.13 on 2024-06-26 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wellnessTracker", "0003_moodscale_is_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moodscale",
            name="is_deleted",
        ),
    ]
